### ISSUE TITLE
项目bug有点多啊

### ISSUE THREAD

**Issue by Minori-ty** [imbacc/vite2-vue3-ssr#1]
能跑起来，但是bug有点多。首先你用的是vue3，App.vue就是#app了，你又再里面套一层。然后是登录不进去

**Comment by imbacc** [comment]
这项目框架还没搭好，搁置了。

**Comment by imbacc** [comment]
> 能跑起来，但是bug有点多。首先你用的是vue3，App.vue就是#app了，你又再里面套一层。然后是登录不进去

这项目框架还没搭好，搁置了。
